package com.example.android.newsreport;

import android.content.Context;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;

/**
 * Created by stupid boy on 4/14/16.
 */
public class CatogeryAdapter extends FragmentPagerAdapter {
    private Context mContext;
private int flag;
    public CatogeryAdapter(int f,Context context, FragmentManager fm) {
        super(fm);this.mContext = context;
flag=f;
    }
    private String tabTitles[] = new String[] { "NEWS","BUSINESS","SPORTS","ARTS","HEALTH","HOME","RECREATION","SCIENCE","SHOPPING","SOCIETY" };
    @Override
    public CharSequence getPageTitle(int position) {
        return tabTitles[position];
    }
    @Override
    public Fragment getItem(int position) {
        if (position == 0) {
            return PageFragment.newInstance(flag,position+1,"http://eventregistry.org/json/article?categoryUri=dmoz%2FNews&ignoreKeywords=&keywords=International&lang=eng&action=getArticles&articlesSortBy=date&resultType=articles&articlesIncludeArticleCategories=true&articlesIncludeArticleLocation=true&articlesIncludeArticleImage=true&articlesIncludeConceptSynonyms=true&articlesIncludeConceptImage=true&articlesIncludeConceptDescription=true&articlesIncludeConceptDetails=true&articlesIncludeConceptTrendingScore=true&articlesIncludeSourceDescription=true&articlesIncludeSourceLocation=true&articlesIncludeSourceImportance=true&articlesIncludeSourceDetails=true&callback=JSON_CALLBACK");
        } else if (position == 1) {
            return PageFragment.newInstance(flag,position+1,"http://eventregistry.org/json/article?categoryUri=dmoz%2FBusiness&ignoreKeywords=&keywords=International&action=getArticles&articlesSortBy=date&resultType=articles&articlesIncludeArticleCategories=true&articlesIncludeArticleLocation=true&articlesIncludeArticleImage=true&articlesIncludeConceptSynonyms=true&articlesIncludeConceptImage=true&articlesIncludeConceptDescription=true&articlesIncludeConceptDetails=true&articlesIncludeConceptTrendingScore=true&articlesIncludeSourceDescription=true&articlesIncludeSourceLocation=true&articlesIncludeSourceImportance=true&articlesIncludeSourceDetails=true&callback=JSON_CALLBACK");
        } else if(position == 2)  {
            return PageFragment.newInstance(flag,position+1,"http://eventregistry.org/json/article?categoryUri=dmoz%2FSports&categoryUri=dmoz%2FGames&ignoreKeywords=&keywords=International&lang=eng&action=getArticles&articlesSortBy=date&resultType=articles&articlesIncludeArticleCategories=true&articlesIncludeArticleLocation=true&articlesIncludeArticleImage=true&articlesIncludeConceptSynonyms=true&articlesIncludeConceptImage=true&articlesIncludeConceptDescription=true&articlesIncludeConceptDetails=true&articlesIncludeConceptTrendingScore=true&articlesIncludeSourceDescription=true&articlesIncludeSourceLocation=true&articlesIncludeSourceImportance=true&articlesIncludeSourceDetails=true&callback=JSON_CALLBACK");
        }
        else if (position==3){return PageFragment.newInstance(flag,position+1,"http://eventregistry.org/json/article?categoryUri=dmoz%2FArts&categoryUri=dmoz%2FArts%2FAnimation&categoryUri=dmoz%2FArts%2FBodyart&categoryUri=dmoz%2FArts%2FEducation&categoryUri=dmoz%2FArts%2FHumanities&categoryUri=dmoz%2FArts%2FVisual_Arts&categoryUri=dmoz%2FArts%2FMusic&categoryUri=dmoz%2FArts%2FLiterature&categoryUri=dmoz%2FArts%2FDesign&categoryUri=dmoz%2FArts%2FCrafts&ignoreKeywords=&keywords=International&lang=eng&action=getArticles&articlesSortBy=date&resultType=articles&articlesIncludeArticleCategories=true&articlesIncludeArticleLocation=true&articlesIncludeArticleImage=true&articlesIncludeConceptSynonyms=true&articlesIncludeConceptImage=true&articlesIncludeConceptDescription=true&articlesIncludeConceptDetails=true&articlesIncludeConceptTrendingScore=true&articlesIncludeSourceDescription=true&articlesIncludeSourceLocation=true&articlesIncludeSourceImportance=true&articlesIncludeSourceDetails=true&callback=JSON_CALLBACK");}
        else if (position==4){return PageFragment.newInstance(flag,position+1,"http://eventregistry.org/json/article?categoryUri=dmoz%2FHealth%2FAddictions&categoryUri=dmoz%2FHealth%2FChild_Health&categoryUri=dmoz%2FHealth&categoryUri=dmoz%2FHealth%2FBeauty&categoryUri=dmoz%2FHealth%2FMen's_Health&categoryUri=dmoz%2FHealth%2FWomen's_Health&categoryUri=dmoz%2FHealth%2FWeight_Loss&categoryUri=dmoz%2FHealth%2FConditions_and_Diseases&categoryUri=dmoz%2FHealth%2FNutrition&categoryUri=dmoz%2FHealth%2FReproductive_Health&ignoreKeywords=&keywords=International&lang=eng&action=getArticles&articlesSortBy=date&resultType=articles&articlesIncludeArticleCategories=true&articlesIncludeArticleLocation=true&articlesIncludeArticleImage=true&articlesIncludeConceptSynonyms=true&articlesIncludeConceptImage=true&articlesIncludeConceptDescription=true&articlesIncludeConceptDetails=true&articlesIncludeConceptTrendingScore=true&articlesIncludeSourceDescription=true&articlesIncludeSourceLocation=true&articlesIncludeSourceImportance=true&articlesIncludeSourceDetails=true&callback=JSON_CALLBACK");}
        else if (position==5){return PageFragment.newInstance(flag,position+1,"http://eventregistry.org/json/article?categoryUri=dmoz%2FHome%2FConsumer_Information&categoryUri=dmoz%2FHome%2FCooking&categoryUri=dmoz%2FHome%2FFamily&categoryUri=dmoz%2FHome%2FHomemaking&categoryUri=dmoz%2FHome%2FPersonal_Finance&categoryUri=dmoz%2FHome%2FPersonal_Organization&categoryUri=dmoz%2FHome%2FRural_Living&ignoreKeywords=&keywords=International&lang=eng&action=getArticles&articlesSortBy=date&resultType=articles&articlesIncludeArticleCategories=true&articlesIncludeArticleLocation=true&articlesIncludeArticleImage=true&articlesIncludeConceptSynonyms=true&articlesIncludeConceptImage=true&articlesIncludeConceptDescription=true&articlesIncludeConceptDetails=true&articlesIncludeConceptTrendingScore=true&articlesIncludeSourceDescription=true&articlesIncludeSourceLocation=true&articlesIncludeSourceImportance=true&articlesIncludeSourceDetails=true&callback=JSON_CALLBACK");}
        else if (position==6){return PageFragment.newInstance(flag,position+1,"http://eventregistry.org/json/article?categoryUri=dmoz%2FRecreation%2FAntiques&categoryUri=dmoz%2FRecreation%2FAudio&categoryUri=dmoz%2FRecreation%2FFood&categoryUri=dmoz%2FRecreation%2FDrugs&categoryUri=dmoz%2FRecreation%2FCamps&categoryUri=dmoz%2FRecreation%2FBirding&categoryUri=dmoz%2FRecreation%2FHumor&categoryUri=dmoz%2FRecreation%2FMotorcycles&categoryUri=dmoz%2FRecreation&categoryUri=dmoz%2FRecreation%2FPets&ignoreKeywords=&keywords=International&lang=eng&action=getArticles&articlesSortBy=date&resultType=articles&articlesIncludeArticleCategories=true&articlesIncludeArticleLocation=true&articlesIncludeArticleImage=true&articlesIncludeConceptSynonyms=true&articlesIncludeConceptImage=true&articlesIncludeConceptDescription=true&articlesIncludeConceptDetails=true&articlesIncludeConceptTrendingScore=true&articlesIncludeSourceDescription=true&articlesIncludeSourceLocation=true&articlesIncludeSourceImportance=true&articlesIncludeSourceDetails=true&callback=JSON_CALLBACK");}
        else if(position==7){return PageFragment.newInstance(flag,position+1,"http://eventregistry.org/json/article?categoryUri=dmoz%2FScience&categoryUri=dmoz%2FScience%2FChemistry&categoryUri=dmoz%2FScience%2FBiology&categoryUri=dmoz%2FScience%2FAstronomy&categoryUri=dmoz%2FScience%2FAnomalies_and_Alternative_Science&categoryUri=dmoz%2FScience%2FMath&categoryUri=dmoz%2FScience%2FPhysics&categoryUri=dmoz%2FScience%2FEarth_Sciences&categoryUri=dmoz%2FScience%2FEducational_Resources&categoryUri=dmoz%2FScience%2FEnvironment&ignoreKeywords=&keywords=International&lang=eng&action=getArticles&articlesSortBy=date&resultType=articles&articlesIncludeArticleCategories=true&articlesIncludeArticleLocation=true&articlesIncludeArticleImage=true&articlesIncludeConceptSynonyms=true&articlesIncludeConceptImage=true&articlesIncludeConceptDescription=true&articlesIncludeConceptDetails=true&articlesIncludeConceptTrendingScore=true&articlesIncludeSourceDescription=true&articlesIncludeSourceLocation=true&articlesIncludeSourceImportance=true&articlesIncludeSourceDetails=true&callback=JSON_CALLBACK");}
        else if(position==8){return PageFragment.newInstance(flag,position+1,"http://eventregistry.org/json/article?categoryUri=dmoz%2FShopping&categoryUri=dmoz%2FShopping%2FChildren&categoryUri=dmoz%2FShopping%2FAuctions&categoryUri=dmoz%2FShopping%2FClothing&categoryUri=dmoz%2FShopping%2FFood&categoryUri=dmoz%2FShopping%2FMusic&categoryUri=dmoz%2FShopping%2FMusic&categoryUri=dmoz%2FShopping%2FConsumer_Electronics&categoryUri=dmoz%2FShopping%2FHealth&categoryUri=dmoz%2FShopping%2FJewelry&ignoreKeywords=&keywords=International&lang=eng&action=getArticles&articlesSortBy=date&resultType=articles&articlesIncludeArticleCategories=true&articlesIncludeArticleLocation=true&articlesIncludeArticleImage=true&articlesIncludeConceptSynonyms=true&articlesIncludeConceptImage=true&articlesIncludeConceptDescription=true&articlesIncludeConceptDetails=true&articlesIncludeConceptTrendingScore=true&articlesIncludeSourceDescription=true&articlesIncludeSourceLocation=true&articlesIncludeSourceImportance=true&articlesIncludeSourceDetails=true&callback=JSON_CALLBACK");}
        else {return PageFragment.newInstance(flag,position+1,"http://eventregistry.org/json/article?categoryUri=dmoz%2FSociety&categoryUri=dmoz%2FSociety%2FActivism&categoryUri=dmoz%2FSociety%2FCrime&categoryUri=dmoz%2FSociety%2FDeath&categoryUri=dmoz%2FSociety%2FFolklore&categoryUri=dmoz%2FSociety%2FPhilanthropy&categoryUri=dmoz%2FSociety%2FPolitics&categoryUri=dmoz%2FSociety%2FReligion_and_Spirituality&categoryUri=dmoz%2FSociety%2FSexuality&categoryUri=dmoz%2FSociety%2FWork&ignoreKeywords=&keywords=International&lang=eng&action=getArticles&articlesSortBy=date&resultType=articles&articlesIncludeArticleCategories=true&articlesIncludeArticleLocation=true&articlesIncludeArticleImage=true&articlesIncludeConceptSynonyms=true&articlesIncludeConceptImage=true&articlesIncludeConceptDescription=true&articlesIncludeConceptDetails=true&articlesIncludeConceptTrendingScore=true&articlesIncludeSourceDescription=true&articlesIncludeSourceLocation=true&articlesIncludeSourceImportance=true&articlesIncludeSourceDetails=true&callback=JSON_CALLBACK"); }
    }



    @Override
    public int getCount() {
        return 10;
    }
}